name: CI for Spring Boot

on:
  push:
    branches:
      - main
      - develop  # Add other branches if needed
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Replace with your project's Java version

      - name: Grant Execute Permission to mvnw
        run: chmod +x ./mvnw

      - name: Build and Test
        run: ./mvnw clean install -DskipTests=false
